server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.168.101:3306/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  security:
    user:
      name: user
      password: 111111

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
